/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    items: Item;
    categories: Category;
    orders: Order;
    reviews: Review;
    'abandoned-carts': AbandonedCart;
    'delivery-settings': DeliverySetting;
    posts: Post;
    'program-participants': ProgramParticipant;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    items: ItemsSelect<false> | ItemsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'abandoned-carts': AbandonedCartsSelect<false> | AbandonedCartsSelect<true>;
    'delivery-settings': DeliverySettingsSelect<false> | DeliverySettingsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'program-participants': ProgramParticipantsSelect<false> | ProgramParticipantsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Primary contact number for orders and updates
   */
  customerNumber?: string | null;
  /**
   * Used to compute delivery charges automatically.
   */
  deliveryZone: 'inside_dhaka' | 'outside_dhaka';
  role: 'admin' | 'user';
  firstName: string;
  lastName: string;
  /**
   * Shipping address used for orders
   */
  address?: {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Optional. Provide descriptive text for accessibility when available.
   */
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items".
 */
export interface Item {
  id: number;
  name: string;
  /**
   * Shown on product highlights and cards.
   */
  shortDescription?: string | null;
  /**
   * Main product copy displayed on the item page.
   */
  description: string;
  price: number;
  image?: (number | null) | Media;
  /**
   * Use this for placeholder images or external image URLs. Either image or imageUrl should be provided.
   */
  imageUrl?: string | null;
  available?: boolean | null;
  category?: (number | null) | Category;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  user?: (number | null) | User;
  /**
   * Captured at order time
   */
  userAgent?: string | null;
  deviceType?: ('mobile' | 'desktop' | 'tablet' | 'other') | null;
  /**
   * Name captured at time of order
   */
  customerName: string;
  customerEmail: string;
  /**
   * Customer contact number captured at time of order
   */
  customerNumber: string;
  paymentMethod: 'cod' | 'bkash' | 'nagad';
  /**
   * Wallet number used to send the payment
   */
  paymentSenderNumber?: string | null;
  /**
   * Reference ID from the mobile wallet payment
   */
  paymentTransactionId?: string | null;
  items: {
    item: number | Item;
    quantity: number;
    id?: string | null;
  }[];
  /**
   * Current status of the order - updates customer via email notifications
   */
  status: 'pending' | 'processing' | 'shipped' | 'completed' | 'cancelled' | 'refunded';
  totalAmount: number;
  subtotal: number;
  shippingCharge: number;
  deliveryZone: 'inside_dhaka' | 'outside_dhaka';
  freeDeliveryApplied?: boolean | null;
  orderDate: string;
  /**
   * Shipping address captured at time of order
   */
  shippingAddress: {
    line1: string;
    line2?: string | null;
    city: string;
    state?: string | null;
    postalCode: string;
    country: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  item: number | Item;
  /**
   * Reviewer (auto-set)
   */
  user: number | User;
  /**
   * Captured from user at time of review
   */
  reviewerName?: string | null;
  rating: number;
  title?: string | null;
  comment: string;
  approved: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abandoned-carts".
 */
export interface AbandonedCart {
  id: number;
  /**
   * Anonymous session identifier for the cart
   */
  sessionId: string;
  user?: (number | null) | User;
  customerName?: string | null;
  customerEmail?: string | null;
  customerNumber?: string | null;
  items?:
    | {
        item: number | Item;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  cartTotal?: number | null;
  status: 'active' | 'abandoned' | 'recovered';
  /**
   * How many recovery reminder emails have been sent
   */
  reminderStage?: number | null;
  lastActivityAt: string;
  recoveredOrder?: (number | null) | Order;
  recoveryEmailSentAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Configure delivery charges and free delivery thresholds.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-settings".
 */
export interface DeliverySetting {
  id: number;
  label: string;
  insideDhakaCharge: number;
  outsideDhakaCharge: number;
  /**
   * Orders equal to or above this amount receive free delivery.
   */
  freeDeliveryThreshold: number;
  /**
   * Applied when the order total is below the free delivery threshold.
   */
  digitalPaymentDeliveryCharge: number;
  shippingHighlightTitle: string;
  shippingHighlightSubtitle: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  author: number | User;
  publishedDate: string;
  category: number | Category;
  featuredImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  excerpt?: string | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-participants".
 */
export interface ProgramParticipant {
  id: number;
  name: string;
  /**
   * 11-digit phone number
   */
  phone: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'items';
        value: number | Item;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'abandoned-carts';
        value: number | AbandonedCart;
      } | null)
    | ({
        relationTo: 'delivery-settings';
        value: number | DeliverySetting;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'program-participants';
        value: number | ProgramParticipant;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  customerNumber?: T;
  deliveryZone?: T;
  role?: T;
  firstName?: T;
  lastName?: T;
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items_select".
 */
export interface ItemsSelect<T extends boolean = true> {
  name?: T;
  shortDescription?: T;
  description?: T;
  price?: T;
  image?: T;
  imageUrl?: T;
  available?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  user?: T;
  userAgent?: T;
  deviceType?: T;
  customerName?: T;
  customerEmail?: T;
  customerNumber?: T;
  paymentMethod?: T;
  paymentSenderNumber?: T;
  paymentTransactionId?: T;
  items?:
    | T
    | {
        item?: T;
        quantity?: T;
        id?: T;
      };
  status?: T;
  totalAmount?: T;
  subtotal?: T;
  shippingCharge?: T;
  deliveryZone?: T;
  freeDeliveryApplied?: T;
  orderDate?: T;
  shippingAddress?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  item?: T;
  user?: T;
  reviewerName?: T;
  rating?: T;
  title?: T;
  comment?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abandoned-carts_select".
 */
export interface AbandonedCartsSelect<T extends boolean = true> {
  sessionId?: T;
  user?: T;
  customerName?: T;
  customerEmail?: T;
  customerNumber?: T;
  items?:
    | T
    | {
        item?: T;
        quantity?: T;
        id?: T;
      };
  cartTotal?: T;
  status?: T;
  reminderStage?: T;
  lastActivityAt?: T;
  recoveredOrder?: T;
  recoveryEmailSentAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-settings_select".
 */
export interface DeliverySettingsSelect<T extends boolean = true> {
  label?: T;
  insideDhakaCharge?: T;
  outsideDhakaCharge?: T;
  freeDeliveryThreshold?: T;
  digitalPaymentDeliveryCharge?: T;
  shippingHighlightTitle?: T;
  shippingHighlightSubtitle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  publishedDate?: T;
  category?: T;
  featuredImage?: T;
  content?: T;
  excerpt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-participants_select".
 */
export interface ProgramParticipantsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}